# Generated by Django 3.2.8 on 2022-02-14 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20220214_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='followed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(default=None, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
