# Generated by Django 3.2.8 on 2022-02-14 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_followers_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ManyToManyField(default=0, null=True, related_name='followedd', to=settings.AUTH_USER_MODEL),
        ),
    ]
