# Generated by Django 3.2.8 on 2022-02-14 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_followers_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followerss',
            field=models.ManyToManyField(null=True, related_name='followeddd', to=settings.AUTH_USER_MODEL),
        ),
    ]
