# Generated by Django 3.2.8 on 2022-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20220216_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeNum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
